import NavBar from "@/components/NavBar"
import '@/app/globals.css'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <body>
      <NavBar/>
      <body>{children}</body>
    </body>
  )
}
